runtime: nodejs14 # or another supported version

instance_class: F2

env_variables:
  BUCKET_NAME: "starparty21"

handlers:
- url: /stylesheets
  static_dir: public/stylesheets
- url: /javascripts
  static_dir: public/javascripts
- url: /img
  static_dir: public/img

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto